/**
 * Profile Check Utility
 *
 * Shared module for hooks that need profile-aware behavior.
 * Reads the runtime profile config generated by profile-loader.js.
 *
 * Usage:
 *   const { getProfileConfig, isLayerActive, getHookConfig } = require('./_profile-check');
 *   if (isLayerActive('homelab')) { ... }
 *   const cfg = getHookConfig('my-hook');
 */

const fs = require('fs');
const path = require('path');

const CONFIG_PATH = path.join(__dirname, '..', 'config', 'profile-config.json');

let _config = null;
let _configMtime = 0;

/**
 * Get the current profile configuration.
 * Caches in memory, reloads if file changed.
 */
function getProfileConfig() {
  try {
    const stat = fs.statSync(CONFIG_PATH);
    const mtime = stat.mtimeMs;

    if (_config && mtime === _configMtime) {
      return _config;
    }

    _config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
    _configMtime = mtime;
    return _config;
  } catch {
    // No profile config - return defaults
    return {
      active_layers: ['general'],
      hook_config: {},
      features: {},
      user_config: {}
    };
  }
}

/**
 * Check if a specific profile layer is active.
 */
function isLayerActive(layerName) {
  const config = getProfileConfig();
  return (config.active_layers || []).includes(layerName);
}

/**
 * Get hook-specific configuration from profile.
 */
function getHookConfig(hookName) {
  const config = getProfileConfig();
  return (config.hook_config || {})[hookName] || {};
}

/**
 * Check if a feature flag is enabled.
 */
function isFeatureEnabled(featureName) {
  const config = getProfileConfig();
  return !!(config.features || {})[featureName];
}

/**
 * Get user configuration value by dot-path.
 */
function getUserConfig(dotPath, defaultValue) {
  const config = getProfileConfig();
  const parts = dotPath.split('.');
  let current = config.user_config || {};

  for (const part of parts) {
    if (current == null || typeof current !== 'object') return defaultValue;
    current = current[part];
  }

  return current !== undefined ? current : defaultValue;
}

module.exports = {
  getProfileConfig,
  isLayerActive,
  getHookConfig,
  isFeatureEnabled,
  getUserConfig
};
