#!/usr/bin/env bash
# Freshness Auditor — AC-08 Maintenance support
# Flags files not modified in >30 days
# Usage: ./freshness-auditor.sh [directory] [days_threshold]
# bash 3.2 compatible (macOS)

BASE_DIR="${1:-/Users/aircannon/Claude/Jarvis/.claude}"
THRESHOLD_DAYS="${2:-30}"
REPORT_DIR="/Users/aircannon/Claude/Jarvis/.claude/reports/maintenance"

audit_freshness() {
    local dir="$1"
    local threshold="$2"
    local stale_count=0
    local total_count=0
    local report_file="$REPORT_DIR/freshness-$(date +%Y-%m-%d).md"

    mkdir -p "$REPORT_DIR"

    echo "# Freshness Audit — $(date +%Y-%m-%d)" > "$report_file"
    echo "" >> "$report_file"
    echo "**Directory**: $dir" >> "$report_file"
    echo "**Threshold**: $threshold days" >> "$report_file"
    echo "" >> "$report_file"
    echo "## Stale Files (>$threshold days since modification)" >> "$report_file"
    echo "" >> "$report_file"
    echo "| File | Last Modified | Days Stale |" >> "$report_file"
    echo "|------|---------------|------------|" >> "$report_file"

    # Use temp file for bash 3.2 compat (no process substitution in pipes)
    local tmpfile
    tmpfile=$(mktemp /tmp/freshness-audit.XXXXXX)
    find "$dir" -type f \( -name "*.md" -o -name "*.yaml" -o -name "*.yml" -o -name "*.json" \) \
        -not -path "*/node_modules/*" -not -path "*/.git/*" 2>/dev/null \
        | sort > "$tmpfile"

    local now_epoch
    now_epoch=$(date +%s)

    while IFS= read -r file; do
        total_count=$((total_count + 1))
        # macOS stat -f for modification time
        local mod_epoch
        mod_epoch=$(stat -f "%m" "$file" 2>/dev/null || true)
        if [ -z "$mod_epoch" ]; then
            continue
        fi
        local age_days=$(( (now_epoch - mod_epoch) / 86400 ))

        if [ "$age_days" -gt "$threshold" ]; then
            stale_count=$((stale_count + 1))
            local mod_date
            mod_date=$(date -r "$mod_epoch" +"%Y-%m-%d" 2>/dev/null || echo "unknown")
            local rel_path="${file#$dir/}"
            echo "| $rel_path | $mod_date | $age_days |" >> "$report_file"
        fi
    done < "$tmpfile"

    rm -f "$tmpfile"

    echo "" >> "$report_file"
    echo "## Summary" >> "$report_file"
    echo "" >> "$report_file"
    echo "- Total files scanned: $total_count" >> "$report_file"
    echo "- Stale files (>$threshold days): $stale_count" >> "$report_file"
    echo "- Fresh files: $((total_count - stale_count))" >> "$report_file"
    echo "" >> "$report_file"
    echo "---" >> "$report_file"
    echo "*Generated by freshness-auditor.sh (AC-08 Maintenance)*" >> "$report_file"

    echo "$report_file"
    return 0
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    audit_freshness "$BASE_DIR" "$THRESHOLD_DAYS"
fi
