#!/usr/bin/env bash
# Organization Auditor — AC-08 Maintenance support
# Validates Jarvis directory structure against expected layout
# Usage: ./organization-auditor.sh
# bash 3.2 compatible (macOS)

JARVIS_ROOT="/Users/aircannon/Claude/Jarvis"
CLAUDE_DIR="$JARVIS_ROOT/.claude"
REPORT_DIR="$CLAUDE_DIR/reports/maintenance"

audit_organization() {
    local issues=0
    local checks=0
    local report_file="$REPORT_DIR/organization-$(date +%Y-%m-%d).md"

    mkdir -p "$REPORT_DIR"

    echo "# Organization Audit — $(date +%Y-%m-%d)" > "$report_file"
    echo "" >> "$report_file"
    echo "## Structure Validation" >> "$report_file"
    echo "" >> "$report_file"
    echo "| Check | Status | Details |" >> "$report_file"
    echo "|-------|--------|---------|" >> "$report_file"

    # Required directories
    local required_dirs=(
        "$CLAUDE_DIR/context"
        "$CLAUDE_DIR/context/components"
        "$CLAUDE_DIR/context/patterns"
        "$CLAUDE_DIR/context/psyche"
        "$CLAUDE_DIR/context/lessons"
        "$CLAUDE_DIR/context/research"
        "$CLAUDE_DIR/context/reference"
        "$CLAUDE_DIR/agents"
        "$CLAUDE_DIR/commands"
        "$CLAUDE_DIR/hooks"
        "$CLAUDE_DIR/skills"
        "$CLAUDE_DIR/scripts"
        "$CLAUDE_DIR/state"
        "$CLAUDE_DIR/state/components"
        "$CLAUDE_DIR/state/queues"
        "$CLAUDE_DIR/config"
        "$CLAUDE_DIR/logs"
        "$CLAUDE_DIR/metrics"
        "$CLAUDE_DIR/reports"
        "$CLAUDE_DIR/plans"
    )

    for dir in "${required_dirs[@]}"; do
        checks=$((checks + 1))
        local rel="${dir#$JARVIS_ROOT/}"
        if [ -d "$dir" ]; then
            echo "| Directory: $rel | PASS | Exists |" >> "$report_file"
        else
            issues=$((issues + 1))
            echo "| Directory: $rel | FAIL | Missing |" >> "$report_file"
        fi
    done

    # Required files
    local required_files=(
        "$JARVIS_ROOT/CLAUDE.md"
        "$CLAUDE_DIR/jarvis-identity.md"
        "$CLAUDE_DIR/context/session-state.md"
        "$CLAUDE_DIR/context/current-priorities.md"
        "$CLAUDE_DIR/context/compaction-essentials.md"
        "$CLAUDE_DIR/context/psyche/capability-map.yaml"
        "$CLAUDE_DIR/context/components/orchestration-overview.md"
        "$CLAUDE_DIR/state/queues/evolution-queue.yaml"
        "$CLAUDE_DIR/state/queues/research-agenda.yaml"
        "$CLAUDE_DIR/config/autonomy-config.yaml"
    )

    echo "" >> "$report_file"
    echo "## Required Files" >> "$report_file"
    echo "" >> "$report_file"
    echo "| File | Status |" >> "$report_file"
    echo "|------|--------|" >> "$report_file"

    for file in "${required_files[@]}"; do
        checks=$((checks + 1))
        local rel="${file#$JARVIS_ROOT/}"
        if [ -f "$file" ]; then
            echo "| $rel | PASS |" >> "$report_file"
        else
            issues=$((issues + 1))
            echo "| $rel | FAIL |" >> "$report_file"
        fi
    done

    # AC State Files
    echo "" >> "$report_file"
    echo "## AC State Files" >> "$report_file"
    echo "" >> "$report_file"
    echo "| Component | State File | Status |" >> "$report_file"
    echo "|-----------|------------|--------|" >> "$report_file"

    local ac_ids=("01-launch" "02-wiggum" "03-review" "04-jicm" "05-reflection" "06-evolution" "07-rd" "08-maintenance" "09-session")
    for ac in "${ac_ids[@]}"; do
        checks=$((checks + 1))
        local state_file="$CLAUDE_DIR/state/components/AC-${ac}.json"
        if [ -f "$state_file" ]; then
            echo "| AC-${ac} | AC-${ac}.json | PASS |" >> "$report_file"
        else
            issues=$((issues + 1))
            echo "| AC-${ac} | AC-${ac}.json | FAIL |" >> "$report_file"
        fi
    done

    echo "" >> "$report_file"
    echo "## Summary" >> "$report_file"
    echo "" >> "$report_file"
    echo "- Total checks: $checks" >> "$report_file"
    echo "- Passed: $((checks - issues))" >> "$report_file"
    echo "- Issues: $issues" >> "$report_file"
    echo "" >> "$report_file"
    echo "---" >> "$report_file"
    echo "*Generated by organization-auditor.sh (AC-08 Maintenance)*" >> "$report_file"

    echo "$report_file"
    return 0
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    audit_organization
fi
