#!/usr/bin/env bash
# Telemetry Dashboard — PR-13.5 Aggregate Summary
# Reads telemetry events and produces a status report
# Usage: ./telemetry-dashboard.sh [date]
# bash 3.2 compatible (macOS)

TELEMETRY_DIR="/Users/aircannon/Claude/Jarvis/.claude/logs/telemetry"
METRICS_DIR="/Users/aircannon/Claude/Jarvis/.claude/metrics"
TARGET_DATE="${1:-$(date +%Y-%m-%d)}"
EVENTS_FILE="$TELEMETRY_DIR/events-${TARGET_DATE}.jsonl"

generate_dashboard() {
    echo "# Jarvis Telemetry Dashboard — $TARGET_DATE"
    echo ""

    # Event counts
    if [ -f "$EVENTS_FILE" ]; then
        local total_events
        total_events=$(wc -l < "$EVENTS_FILE" | tr -d ' ')
        echo "## Event Summary"
        echo ""
        echo "- **Total events**: $total_events"
        echo "- **Events file**: $EVENTS_FILE"
        echo ""

        # Component breakdown
        echo "## Component Activity"
        echo ""
        echo "| Component | Events |"
        echo "|-----------|--------|"

        if command -v jq >/dev/null 2>&1; then
            jq -r '.component' "$EVENTS_FILE" 2>/dev/null | sort | uniq -c | sort -rn | while read -r count comp; do
                echo "| $comp | $count |"
            done
        else
            echo "| (jq not available) | — |"
        fi

        echo ""

        # Event types
        echo "## Event Types"
        echo ""
        echo "| Type | Count |"
        echo "|------|-------|"

        if command -v jq >/dev/null 2>&1; then
            jq -r '.event_type' "$EVENTS_FILE" 2>/dev/null | sort | uniq -c | sort -rn | while read -r count etype; do
                echo "| $etype | $count |"
            done
        fi
    else
        echo "## No Events"
        echo ""
        echo "No telemetry events found for $TARGET_DATE."
    fi

    echo ""

    # AC Status
    echo "## AC Component Status"
    echo ""
    echo "| AC | Name | Status |"
    echo "|----|------|--------|"

    local state_dir="/Users/aircannon/Claude/Jarvis/.claude/state/components"
    for f in "$state_dir"/AC-*.json; do
        if [ -f "$f" ] && command -v jq >/dev/null 2>&1; then
            local comp name status
            comp=$(jq -r '.component // "?"' "$f" 2>/dev/null)
            name=$(jq -r '.name // "?"' "$f" 2>/dev/null)
            status=$(jq -r '.status // "?"' "$f" 2>/dev/null)
            echo "| $comp | $name | $status |"
        fi
    done

    echo ""

    # Metrics summary
    echo "## Metrics Directories"
    echo ""
    local dirs=("aggregates" "baselines" "benchmarks" "scores" "test-results")
    for d in "${dirs[@]}"; do
        local dir_path="$METRICS_DIR/$d"
        if [ -d "$dir_path" ]; then
            local file_count
            file_count=$(find "$dir_path" -type f 2>/dev/null | wc -l | tr -d ' ')
            echo "- **$d/**: $file_count files"
        fi
    done

    echo ""
    echo "---"
    echo "*Generated by telemetry-dashboard.sh (PR-13.5)*"
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    generate_dashboard
fi
